name: Trigger Jepsen Tests
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      rabbitmq_version:
        description: 'RabbitMQ version (e.g. 3.13.0-alpha.278)'
        required: true
        type: string

jobs:
  dispatch:
    runs-on: ubuntu-22.04
    steps:
      - name: Get RabbitMQ version
        run: |
          TAG=${{ github.event.release.tag_name }}
          VERSION=$(echo $TAG | cut -c2-)
          echo "rabbitmq_version=$VERSION" >> $GITHUB_ENV
          MAJOR=$(echo $VERSION | cut -f1 -d'.')
          MINOR=$(echo $VERSION | cut -f2 -d'.')
          BRANCH=$MAJOR$MINOR
          echo "rabbitmq_branch=$BRANCH" >> $GITHUB_ENV
      - name: Dispatch event to trigger Jepsen tests
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: new_alpha_${{ env.rabbitmq_branch }}
          repository: rabbitmq/jepsen
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          client-payload: >-
            {"version": "${{ env.rabbitmq_version }}"}
